# Generated by Django 5.2 on 2025-04-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quadra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da quadra')),
                ('endereco', models.TextField(help_text='Informe o endereço no formato: Logradouro, endereço, Bairro, Cidade, Estado', verbose_name='Localidade')),
                ('estrutura_fisica', models.TextField(help_text='Descreva a estrutura física da quadra', verbose_name='Estrutura física da quadra')),
                ('informacoes_jogos', models.TextField(help_text='Descreva os dias e horários dos jogos', verbose_name='Informações sobre os jogos')),
            ],
        ),
    ]
