# Generated by Django 5.2 on 2025-04-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quadras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quadra',
            name='estrutura_fisica',
            field=models.TextField(blank=True, help_text='Descreva a estrutura física da quadra', null=True, verbose_name='Estrutura física da quadra'),
        ),
        migrations.AlterField(
            model_name='quadra',
            name='informacoes_jogos',
            field=models.TextField(blank=True, help_text='Descreva os dias e horários dos jogos', null=True, verbose_name='Informações sobre os jogos'),
        ),
    ]
